### ISSUE TITLE
Feedback and request

### ISSUE THREAD

**Issue by ghost** [kvq/SuperTrails#1]
First of, thanks for this amazing plugin!

Block trails: 
- Ore Blocks: Missing redstone, lapis and emerald ores

Requests:
- New block ore tracks (See photo)
- More rain trails
- Ideas: All of the smaller things, like button, mushroom, torch, lever etc.
- In general a track with each different block type could be nice. 
- Option to could limit different colour on wings to different classes.

![2016-06-27_13 15 33](https://cloud.githubusercontent.com/assets/10177986/16378282/47e3ccbe-3c6b-11e6-8565-49e5e1d9ee52.png)

**Comment by kvq** [comment]
Great idea ! Added to todo list :D
